// <auto-generated />
using System;
using ElectronicsVendor.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElectronicsVendor.Migrations
{
    [DbContext(typeof(ElectronicsVendorContext))]
    [Migration("20230315211834_ModelLine2")]
    partial class ModelLine2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ElectronicsVendor.Models.Component", b =>
                {
                    b.Property<int>("ComponentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("ComponentId");

                    b.ToTable("Components");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.ComponentVendor", b =>
                {
                    b.Property<int>("ComponentVendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<int?>("ModelLineId")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("ComponentVendorId");

                    b.HasIndex("ComponentId");

                    b.HasIndex("ModelLineId");

                    b.HasIndex("VendorId");

                    b.ToTable("ComponentVendors");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.ModelLine", b =>
                {
                    b.Property<int>("ModelLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("ModelLineId");

                    b.HasIndex("ComponentId");

                    b.ToTable("ModelLines");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("VendorId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.ComponentVendor", b =>
                {
                    b.HasOne("ElectronicsVendor.Models.Component", "Component")
                        .WithMany("JoinEntities")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElectronicsVendor.Models.ModelLine", null)
                        .WithMany("JoinEntities")
                        .HasForeignKey("ModelLineId");

                    b.HasOne("ElectronicsVendor.Models.Vendor", "Vendor")
                        .WithMany("JoinEntities")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.ModelLine", b =>
                {
                    b.HasOne("ElectronicsVendor.Models.Component", "Component")
                        .WithMany("ModelLines")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.Component", b =>
                {
                    b.Navigation("JoinEntities");

                    b.Navigation("ModelLines");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.ModelLine", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("ElectronicsVendor.Models.Vendor", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
